POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My second post jou",
    "author": "Mr Authorman",
    "url": "www.someurl.smth",
    "likes": "123",
    "user": "61e5b3616714ea357189b8b4"
}